#NAME: Alexander Ma
#EMAIL: alexanderzma@hotmail.com
#ID: 105093055

FILES=README Makefile connected.png build_run.png copy.png git.png my_beaglebone.jpg

default: $(FILES)
	tar -czf lab4a-105093055.tar.gz $(FILES)